name: GitHub Actions
on: [push]
jobs:
  Test:
    runs-on: flutter-runner-kintosh
    steps:
      - run: export PATH=$PATH:/Users/cesarurrego/Development/flutter/bin
      - run: flutter test
  Documentation:
    runs-on: flutter-runner-kintosh
    steps:
      - run: export PATH=$PATH:/Users/cesarurrego/Development/flutter/bin
      - run: export PATH=$PATH:/Users/cesarurrego/.pub-cache/bin/
      - run: dartdoc
  android_build:
    runs-on: flutter-runner-kintosh
    steps:
    - run: export PATH=$PATH:/Users/cesarurrego/Development/flutter/bin
    - run: export PATH=$PATH:/Users/cesarurrego/Library/Android/sdk//tools
    - run: export PATH=$PATH:/Users/cesarurrego/Library/Android/sdk//platform-tools
    - run: flutter packages get
    - run: flutter clean
    - run: flutter build apk