name:  Build and Test Flutter App
on: [push,pull_request]

jobs:

  test:
    runs-on: macos-latest
    #sequence of tasks called
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: flutter pub get
    - run: flutter test

  documentation:
    runs-on: macos-latest
    needs: test
    #sequence of tasks called
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'beta', 'dev' or 'master'
    - run: dartdoc

  build_android:
    runs-on: macos-latest
    needs: test
    #sequence of tasks called
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle

  build_ios:
    runs-on: macos-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign